### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by thelucyclub** [iServer-Project/iServer#1]
- [x] Initial Commit
  - [x] Player implantation
  - [x] Basic movement method
- [x] Plugins
  - [x] Plugin support
  - [x] Example format
- [ ] Proxy and Transfer Addon
  - [x] DNS Lookup
  - [x] Backwards compatibility
  - [ ] Set lobby / hub
  - [ ] Set arbitrary locations

**Comment by matthew4444** [comment]
i might be able to help u

**Comment by matthew4444** [comment]
im on many plugin dev teams that make custom pmmp server versions and stuff like that,and etc

**Comment by matthew4444** [comment]
just ask if u want any help from our plugin dev teams

**Comment by matthew4444** [comment]
if u need it

**Comment by thelucyclub** [comment]
@matthew4444 sorry, this is coded in BEEF-SCI (a custom language) and may be hard for you to understand. It is simple (to me) and easy to learn (to me) and should not be much work if you're willing to.

**Comment by matthew4444** [comment]
i would
